sonar.projectKey=tier4_ota-image-libs-go
sonar.organization=tier4
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.tests.reportPaths=.test/report.json
sonar.go.coverage.reportPaths=.test/*/coverage.out