name: test CI

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test.yaml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [main]
  # allow the test CI to be manually triggerred
  workflow_dispatch:

jobs:
  go-test:
    name: Run go test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        id: go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Go test
        run: |
          mkdir -p ./.test
          go test -coverprofile ./.test/coverage.out -json -v ./artifact 2>&1 | tee ./.test/report.json

      - name: Upload test results
        uses: sonarsource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
